GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "Title",
    "author": "Author",
    "url": "Url",
    "likes": 111
}

###
DELETE http://localhost:3003/api/blogs/63cf39a80eb98aee8bde3843

###
PUT http://localhost:3001/api/notes/63c9b73ba0add8312d169214
content-type: application/json

{
    "title": "Title",
    "author": "Author",
    "url": "Url",
    "likes": 111
}

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}