GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/10000

###
DELETE http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Test01",
    "number": "1111111111"
}

###
PUT http://localhost:3001/api/persons/
content-type: application/json

{
    id: 1,
    content: "HTML is easy",
    date: "2022-05-30T17:30:31.098Z",
    important: true
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{

}